<button id="button">
    <span><?= $block->escapeHtml(__('Press here to get POPUP')) ?></span>
</button>

<div id="modal">
    <div class="modal-body-content">

        <h1><?= $block->escapeHtml(__('Popup ')) ?></h1>

    </div>
</div>

<script type="text/javascript">
    require([
        "jquery",
        "Magento_Ui/js/modal/modal"
    ],function($, modal) {

        var options = {
            type: 'popup',
            responsive: true,
            title: 'Main title',
            buttons: [{
                text: $.mage.__('Ok'),
                class: '',
                click: function () {
                    this.closeModal();
                }
            }]
        };

        var popup = modal(options, $('#modal'));
        $("#button").click(function() {
            $('#modal').modal('openModal');
        });
    });
</script>

